### PR TITLE
Update ecds.json

### PR DESCRIPTION
**Pull request by MadinaHasan19**

### CODE REVIEW

**Comment by Joe-Heffer-Shef** [comment]
I tested this using this SQL query:

```sql
SELECT
   CAST(AGE_AT_ARRIVAL AS INTEGER) AS AGE_AT_ARRIVAL
  ,CAST(ARRIVAL_DATE AS DATE) AS ARRIVAL_DATE
  ,CAST(ASSESSMENT_DATE AS DATE) AS ASSESSMENT_DATE
  ,CAST(ASSESSMENT_TIME AS TIME) AS ASSESSMENT_TIME
  ,CAST(DECIDED_TO_ADMIT_DATE AS DATE) AS DECIDED_TO_ADMIT_DATE
  ,CAST(DECIDED_TO_ADMIT_TIME AS TIME) AS DECIDED_TO_ADMIT_TIME
  ,CAST(DEPARTURE_DATE AS DATE) AS DEPARTURE_DATE
  ,CAST(DEPARTURE_TIME AS TIME) AS DEPARTURE_TIME
  ,CAST(EXPIRY_DATE_1 AS DATE) AS EXPIRY_DATE_1
  ,CAST(EXPIRY_DATE_2 AS DATE) AS EXPIRY_DATE_2
  ,CAST(EXPIRY_DATE_3 AS DATE) AS EXPIRY_DATE_3
  ,CAST(EXPIRY_DATE_4 AS DATE) AS EXPIRY_DATE_4
  ,CAST(EXPIRY_TIME_1 AS TIME) AS EXPIRY_TIME_1
  ,CAST(EXPIRY_TIME_2 AS TIME) AS EXPIRY_TIME_2
  ,CAST(FRACTIONAL_AGE_AT_ARRIVAL AS DOUBLE) AS FRACTIONAL_AGE_AT_ARRIVAL
  ,CAST(INITIAL_ASSESSMENT_TIME_SINCE_ARRIVAL AS INTEGER) AS INITIAL_ASSESSMENT_TIME_SINCE_ARRIVAL
  ,CAST(INJURY_DATE AS DATE) AS INJURY_DATE
  ,CAST(PERIOD_END_DATE AS DATE) AS PERIOD_END_DATE
  ,CAST(PERIOD_LENGTH AS STRING) AS PERIOD_LENGTH
  ,CAST(PERIOD_START_DATE AS DATE) AS PERIOD_START_DATE
  ,CAST(REFERRAL_ASSESSMENT_DATE_1 AS DATE) AS REFERRAL_ASSESSMENT_DATE_1
  ,CAST(REFERRAL_ASSESSMENT_DATE_2 AS DATE) AS REFERRAL_ASSESSMENT_DATE_2
  ,CAST(REFERRAL_ASSESSMENT_DATE_3 AS DATE) AS REFERRAL_ASSESSMENT_DATE_3
  ,CAST(REFERRAL_ASSESSMENT_DATE_4 AS DATE) AS REFERRAL_ASSESSMENT_DATE_4
  ,CAST(SEEN_DATE AS DATE) AS SEEN_DATE
  ,CAST(SERVICE_REQUEST_DATE_1 AS DATE) AS SERVICE_REQUEST_DATE_1
  ,CAST(SERVICE_REQUEST_DATE_2 AS DATE) AS SERVICE_REQUEST_DATE_2
  ,CAST(SERVICE_REQUEST_DATE_3 AS DATE) AS SERVICE_REQUEST_DATE_3
  ,CAST(SERVICE_REQUEST_DATE_4 AS DATE) AS SERVICE_REQUEST_DATE_4
  ,CAST(START_DATE_1 AS DATE) AS START_DATE_1
  ,CAST(START_DATE_2 AS DATE) AS START_DATE_2
  ,CAST(START_DATE_3 AS DATE) AS START_DATE_3
  ,CAST(START_DATE_4 AS DATE) AS START_DATE_4
  ,CAST(START_TIME_1 AS TIME) AS START_TIME_1
  ,CAST(TREATMENT_DATE_1 AS DATE) AS TREATMENT_DATE_1
  ,CAST(TREATMENT_DATE_10 AS DATE) AS TREATMENT_DATE_10
  ,CAST(TREATMENT_DATE_11 AS DATE) AS TREATMENT_DATE_11
  ,CAST(TREATMENT_DATE_12 AS DATE) AS TREATMENT_DATE_12
  ,CAST(TREATMENT_DATE_2 AS DATE) AS TREATMENT_DATE_2
  ,CAST(TREATMENT_DATE_3 AS DATE) AS TREATMENT_DATE_3
  ,CAST(TREATMENT_DATE_4 AS DATE) AS TREATMENT_DATE_4
  ,CAST(TREATMENT_DATE_5 AS DATE) AS TREATMENT_DATE_5
  ,CAST(TREATMENT_DATE_6 AS DATE) AS TREATMENT_DATE_6
  ,CAST(TREATMENT_DATE_7 AS DATE) AS TREATMENT_DATE_7
  ,CAST(TREATMENT_DATE_8 AS DATE) AS TREATMENT_DATE_8
  ,CAST(TREATMENT_DATE_9 AS DATE) AS TREATMENT_DATE_9
FROM read_csv_auto('/mnt/sdd/hes_ecds/*.txt', delim='|', all_varchar=TRUE)
USING SAMPLE 100;
```

which I ran using DuckDB:

```bash
$ duckdb -c "$query"
```

**Review by Joe-Heffer-Shef — APPROVED** [review]

**Comment by Joe-Heffer-Shef** [comment]
It looks like some of the columns named `*TIME*` might work using the `time` data type also.

**Comment by MadinaHasan19** [comment]
Thanks Joe, which time fields did not work as time?

**Comment by MadinaHasan19** [comment]
> Thanks Joe, which time fields did not work as time?

from the code above only INITIAL_ASSESSMENT_TIME_SINCE_ARRIVAL is typed as integer. All other time fields are as time. If that works I will try it.

**Comment by Joe-Heffer-Shef** [comment]
Yeah, it looks like there's a few TIME, INTEGER and DATE fields in there
https://github.com/CUREd-Plus/cuRed/blob/main/scripts/sql/hes_ecds/hes_ecds_cast_sample_csv.sql

**Comment by Joe-Heffer-Shef** [comment]
This metadata can be updated based on NHS Metadata Dashboard

**Pull request merged**
